# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  pipelines:
  - pipeline: terraformBuild
    source: terraform-build
    trigger: 
      branches:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '7cd340d9-81b0-475b-9481-1acbace7a39e'
    definition: '3'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    artifactName: 'terraform-build-artifact'
    targetPath: '$(Pipeline.Workspace)'

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-build-artifact/terraform'
    backendServiceArm: 'Free Trial Subscription(da17c1f2-92e5-4bfe-971b-b3692b8b50f3)'
    backendAzureRmResourceGroupName: 'terraform-state-rg'
    backendAzureRmStorageAccountName: 'terraformstate1sj'
    backendAzureRmContainerName: 'terraform'
    backendAzureRmKey: 'terraform.tfstate'