# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  pipelines:
  - pipeline: terraformBuild
    source: terraform-build
    trigger: 
      branches:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.19'

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    backendServiceArm: 'Free Trial Subscription(da17c1f2-92e5-4bfe-971b-b3692b8b50f3)'
    backendAzureRmResourceGroupName: 'terraform-state-rg'
    backendAzureRmStorageAccountName: 'terraformstate1sj'
    backendAzureRmContainerName: 'terraform'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    environmentServiceNameAzureRM: 'Free Trial Subscription(da17c1f2-92e5-4bfe-971b-b3692b8b50f3)'

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'Free Trial Subscription(da17c1f2-92e5-4bfe-971b-b3692b8b50f3)'