# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Terraform@2
  inputs:
    TemplatePath: 'terraform'
    Arguments: 'init'
    PlanPath: 'terraform'
    InstallTerraform: true
    UseAzureSub: true
    ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
    ConnectedServiceNameARM: 'Free Trial Subscription(da17c1f2-92e5-4bfe-971b-b3692b8b50f3)'
    ManageState: false

